# Jekyll: https://jekyllrb.com/docs/configuration/

## Default Configuration: https://jekyllrb.com/docs/configuration/default/

future                   : true

### Conversion
markdown                 : kramdown
highlighter              : rouge

### Outputting
permalink                : /:categories/:title/
paginate_path            : /:num
timezone                 : "Europe/Warsaw" # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

### Where things are
include:
  - _collections
  - _pages

sass:
  #  sass_dir: ui/_scss
  style: compressed

## Collections: https://jekyllrb.com/docs/collections/
collections_dir          : _collections
collections:
  categories:
    output               : true
    permalink            : /:collection/:path/
  tags:
    output               : true
    permalink            : /:collection/:path/
  langs:
    output               : true
    permalink            : /:collection/:path/
  tools:
    output               : true
    permalink            : /:collection/:path/
  libs:
    output               : true
    permalink            : /:collection/:path/
  projects:
    output               : true
    permalink            : /:collection/:path/
  eso:
    output               : true
    permalink            : /:collection/:path/
  books:
    output               : true
    permalink            : /:collection/:path/

## Front Matter Defaults: https://jekyllrb.com/docs/configuration/front-matter-defaults/

defaults:
  # _posts
  - scope:
      path               : ""
      type               : posts
    values:
      layout             : post
      read_time          : true
      comments           : true
      share              : true
      related            : false
      pagination         : true
      toc: true
      toc_sticky         : true
      sidebar:
        nav              : sidebar-main
  # _pages
  - scope:
      path               : "_pages"
      type               : pages
    values:
      layout             : page
      classes            : wide
      sidebar            :
        main             : true
        nav              : sidebar-main
  # _categories
  - scope:
      path               : ""
      type               : categories
    values:
      layout             : page-category
      share              : true
      classes            : wide
      sidebar:
        main             : true
        nav              : sidebar-main
  # _tags
  - scope:
      path               : ""
      type               : tags
    values:
      layout             : page-tag
      share              : true
      classes            : wide
      sidebar:
        main             : true
        nav              : sidebar-main
  # _langs
  - scope:
      path               : ""
      type               : langs
    values               :
      layout             : page-lang
      share              : true
      classes            : wide
      sidebar:
        main             : true
        nav              : sidebar-main
  # _tools
  - scope:
      path               : ""
      type               : tools
    values:
      layout             : page-tool
      share              : true
      classes            : wide
      sidebar:
        main             : true
        nav              : sidebar-main
  # _libs
  - scope:
      path               : ""
      type               : libs
    values:
      layout             : page-lib
      share              : true
      classes            : wide
      sidebar:
        main             : true
        nav              : sidebar-main
  # _projects
  - scope:
      path               : ""
      type               : projects
    values:
      layout             : page-project
      share              : true
      classes            : wide
      sidebar:
        main             : true
        nav              : sidebar-main
  # _eso
  - scope:
      path               : ""
      type               : eso
    values:
      layout             : page-eso
      share              : true
      classes            : wide
      sidebar:
        main             : true
        nav              : sidebar-main
  # _books
  - scope:
      path               : ""
      type               : books
    values:
      layout             : page-book
      share              : true
      classes            : wide
      sidebar:
        main             : true
        nav              : sidebar-main

# Plugins
plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-mentions
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-sass-converter
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings

## jekyll-commonmark-ghpages
commonmark:
  options                : ["SMART", "FOOTNOTES"]
  extensions             : ["strikethrough", "autolink", "table", "tagfilter"]

## jekyll-mentions
jekyll-mentions:
  base_url               : "https://twitter.com"

## jekyll-paginate
paginate                 : 1

## jekyll-remote-theme
remote_theme             : twocolumn/minimal-mistakes@gh-pages

## jekyll-seo-tag
title                    : "WriteOnly.pl"
tagline                  : "WriteOnly Haskell, Scala, Jekyll, Git & Bash Blog"
description: >-
  Blog o programowaniu w językach Haskell, Scala Native i Scala.js
  oraz generatorze stron Jekyll, systemie kontroli wersji Git i użyciu wiersza poleceń CLI
url                      :
author:
  twitter                : "TheKamilAdam"
  name                   : "Kamil Adam"
  avatar                 : "/assets/images/kamil.adam.jpg"
  bio                    : "Senior Java/Scala/Kotlin Developer"
twitter:
  username               : "TheKamilAdam"
facebook:
logo                     : "/favicon-32x32.png"
social:
  name      : "Kamil Adam"
  links:
    - https://github.com/writeonly
    - https://www.linkedin.com/company/writeonly-pl
    - https://www.facebook.com/WriteOnlyPL
    - https://www.instagram.com/degustujacaistota/
    - https://twitter.com/TheKamilAdam
    - https://www.tumblr.com/blog/thekamiladam
    - https://www.reddit.com/user/WriteOnlyPL
    - https://dev.to/kamiladam

# External systems

## Compress HTML
compress_html:
  clippings              : all
  comments               : all
  endings                : all
  profile                : false
  startings              : [html, head, body]

## Analytics
analytics:
  provider               : "google-gtag"
  google:
    tracking_id          : "UA-136426906-1"
    anonymize_ip         : false

## Comments
comments:
  provider               : "disqus-follow"
  disqus:
    shortname            : "writeonly-pl"

## Search
search                   : follow
search_follow            : true
search_full_content      : true
#search_provider          : "search-jekyll"
search_provider          : "google"
google:
  search_engine_id       : "bf18084b82c20452c"
  instant_search         : false # false (default), true
  search_instant         : true # false (default), true

ad_sense:
  ad_sense_id            : "ca-pub-8978320289517812"
  all                    : false

web_vitals               : false

## Social Sharing
og_image                 : "/favocon.ico"
footer:
  links:
    - label              : "GitHub"
      icon               : "fab fa-fw fa-github"
      url                : "https://github.com/writeonly"
    - label              : "Linkedin"
      icon               : "fab fa-fw fa-linkedin"
      url                : "https://www.linkedin.com/company/writeonly-pl/"
    - label              : "Facebook"
      icon               : "fab fa-fw fa-facebook"
      url                : "https://www.facebook.com/WriteOnlyPL"
    - label              : "Instagram"
      icon               : "fab fa-fw fa-instagram"
      url                : "https://instagram.com/degustujacaistota"
    - label              : "Twitter"
      icon               : "fab fa-fw fa-twitter"
      url                : "https://twitter.com/TheKamilAdam"
    - label              : "Tumblr"
      icon               : "fab fa-fw fa-tumblr"
      url                : "https://writeonly-pl.tumblr.com"
    - label              : "Reddit"
      icon               : "fab fa-fw fa-reddit"
      url                : "https://www.reddit.com/user/WriteOnlyPL"
    - label              : "Dev.to"
      icon               : "fab fa-fw fa-dev"
      url                : "https://dev.to/kamiladam"

# Theme settings
locale                   : "pl-PL"

masthead_title           : "Blog o programowaniu w językach Haskell, Scala Native i Scala.js"
subtitle                 : "oraz generatorze stron Jekyll, systemie kontroli wersji Git i użyciu wiersza poleceń CLI"
email                    : "kamil.adam.zabinski@gmail.com"

repository               : "writeonly/writeonly.github.io"
twitter_username         : "TheKamilAdam"
github_username          : "kamil-adam"

minimal_mistakes_skin    : "gold"
breadcrumbs              : true
words_per_minute         : 100

critical_css             : true

## Scripts
scripts:
  - https://code.jquery.com/jquery-3.5.1.slim.min.js
  - /assets/js/first.min.js

## Font Awesome
fontawesome:
  use                    : js # "sass", "js"
  solid                  : true
  regular                : true
  brands                 : true

## Archives
category_archive:
  type                   : collection
  path                   : /categories/
tag_archive:
  type                   : collection
  path                   : /tags/
